name: Create S3 bucket

on:
  workflow_dispatch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Workspace
        run: terraform workspace new ${{ env.environment }}

      - name: Terraform Init
        working-directory: aws_s3_bucket
        run: |
          terraform init

      - name: Terraform Format
        working-directory: aws_s3_bucket
        run: terraform fmt

      - name: Terraform Plan
        working-directory: aws_s3_bucket
        run: terraform workspace select ${{ env.environment }} && terraform plan

      - name: Terraform Apply
        working-directory: aws_s3_bucket
        run: terraform workspace select ${{ env.environment }} && terraform apply -auto-approve